name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'gateway/**'
      - 'dog-eks-cluster/**'
      - 'lambda/**'

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    environment: dev
    
    strategy:
      matrix:
        directory: ['gateway', 'dog-eks-cluster', 'lambda']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        working-directory: ${{ matrix.directory }}
        env:
          TF_VAR_account_id: ${{ secrets.TF_VAR_ACCOUNT_ID }}
          TF_VAR_eks_cluster_role_arn: ${{ secrets.TF_VAR_EKS_CLUSTER_ROLE_ARN }}
          TF_VAR_eks_node_group_role_arn: ${{ secrets.TF_VAR_EKS_NODE_GROUP_ROLE_ARN }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ matrix.directory }}
        env:
          TF_VAR_account_id: ${{ secrets.TF_VAR_ACCOUNT_ID }}
          TF_VAR_eks_cluster_role_arn: ${{ secrets.TF_VAR_EKS_CLUSTER_ROLE_ARN }}
          TF_VAR_eks_node_group_role_arn: ${{ secrets.TF_VAR_EKS_NODE_GROUP_ROLE_ARN }}
        run: terraform plan -out=tfplan

  deploy:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform
    environment:
      name: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Apply
        working-directory: ${{ matrix.directory }}
        env:
          TF_VAR_account_id: ${{ secrets.TF_VAR_ACCOUNT_ID }}
          TF_VAR_eks_cluster_role_arn: ${{ secrets.TF_VAR_EKS_CLUSTER_ROLE_ARN }}
          TF_VAR_eks_node_group_role_arn: ${{ secrets.TF_VAR_EKS_NODE_GROUP_ROLE_ARN }}
        run: terraform apply -auto-approve tfplan
