name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'gateway/**'
      - 'cluster/**'
      - 'lambda/**'

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ['gateway', 'cluster', 'lambda']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        working-directory: ${{ matrix.directory }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ matrix.directory }}
        run: terraform plan -out=tfplan

  deploy:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform
    environment:
      name: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Apply
        working-directory: ${{ matrix.directory }}
        run: terraform apply -auto-approve tfplan
